name: shell-format

on: [push, pull_request]
# TODO only master branch

jobs:
  shell-format:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
    - name: Install shfmt
      run: sudo snap install shfmt
    - name: Check shell script formatting
      run: shfmt -d .
