name: Tests

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  shell-format:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: Install shfmt
      run: sudo snap install shfmt
    - name: Check shell script formatting
      run: shfmt -d .

  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: Install shellcheck
      run: sudo apt install shellcheck
    - name: Static analysis of shell script
      run: shellcheck setup.sh
